#include <stdio.h>
#include <stdlib.h>
/**
* main -  term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89.
*
* Return: Always (Success)
*/
int main(void)
{
	double a = 0;
	double b = 1;
	double f;
	int i;

	for (i = 0; i < 50; i++)
	{
		f = a + b;
		if (i != 49)
			printf("%.f, ", f);
		else
			printf("%.f\n", f);
		a = b;
		b = f;
	}
	return (0);
}
